name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Set name
        run: git config --global user.email "you@example.com"
      - name: Set name
        run: git config --global user.name "Workflow"
      - name: Deploy
        run: npm run deploy --repo=https://github.com/trollrar/calc-tamia.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
